### ISSUE TITLE
configure with react native 

### ISSUE THREAD

**Issue by azamkth** [graphcool-examples/expo-auth0-example#2]
Hi, Could you please tell me how did you configure jwt-decode with react-native.
i run command npm install jwt-decode
and then try to use like import jwtDecoder from 'jwt-decode'

but i am getting error : unable to resolve module jwt-decode

**Comment by avantbaker** [comment]
@azamkth it may be an issue with your package.json perhaps a trailing comma inside of one of the objects, an incorrect import.. for instance

`import jwtDecoder from 'jwt-decode`
when it should be
`import { jwtDecoder } from 'jwt-decode`

**Comment by azamkth** [comment]
thanks :). problem has been fixed
